export const TEST_ACTION = 'TEST_ACTION';
export const INCREMENT_SYNC = 'INCREMENT_SYNC';
export const DECREMENT_SYNC = 'DECREMENT_SYNC';

export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const DECREMENT_ASYNC = 'DECREMENT_ASYNC';
export const DECREMENT_ASYNC_TWICE = 'DECREMENT_ASYNC_TWICE';